### ISSUE TITLE
Roadmap to 5.0.0

### ISSUE THREAD

**Issue by legokichi** [Ikagaka/NamedManager.js#19]
# 4.1.0

* [ ] char*.bindgroup*.addid,ID
* [ ] char*.menuitem*,ID
* [ ] seriko.paint_transparent_region_black,数値
* [ ] seriko.use_self_alpha,数値

# 4.2.0

* [ ] menu,hidden, char*.menu,autoまたはhidden
* [ ] char*.alignmenttodesktop, top
* [ ] char*.defaultx,X座標, char*.defaulty,Y座標

# in the distant future...

* メニューの背景や色
* おすわリリー
